double_mantas:
    resource: "@DoubleMantasBundle/Resources/config/routing.yml"

double_vytautas:
    resource: "@DoubleVytautasBundle/Resources/config/routing.yml"
    prefix:   /
    
double_julius:
    resource: "@DoubleJuliusBundle/Resources/config/routing.yml"
    prefix:   /

double_blog:
    resource: "@DoubleBlogBundle/Resources/config/routing.yml"
    prefix:   /

